### ISSUE TITLE
Sketches won't compile in SMCE 1.2.1

### ISSUE THREAD

**Issue by Spidergirl93** [DIT112-V21/group-10#74] opened 2021-05-12 07:31 UTC
OtherCars in Arduino folder cannot be compiled in the master branch. Fix it!

**Comment by lucasnordic** [comment] 2021-05-12 08:16
https://discord.com/channels/823515675367702558/823998556553478226/841350531224961044

The problem is with this line of code in the .ino:
    mqtt.onMessage([](String topic, String message) {

**Comment by lucasnordic** [comment] 2021-05-24 15:27
Closing this since no-one is using 1.2.1

**Closed as completed by lucasnordic** 2021-05-24 15:27 UTC
Labels: bug
